% Filter specs
fp = 0.4;
fs = 0.5;
Rp = -20*log10(1-0.1);   % ≈ 0.915 dB
Rs = 40;                 % 40 dB attenuation

% --- Equiripple FIR ---
d_equ = designfilt('lowpassfir', ...
    'DesignMethod','equiripple', ...
    'PassbandFrequency',fp, ...
    'StopbandFrequency',fs, ...
    'PassbandRipple',Rp, ...
    'StopbandAttenuation',Rs);

% --- Butterworth (NO ripple param allowed) ---
d_butt = designfilt('lowpassiir', ...
    'DesignMethod','butter', ...
    'PassbandFrequency',fp, ...
    'StopbandFrequency',fs, ...
    'StopbandAttenuation',Rs, ...
    'MatchExactly','stopband');

% --- Chebyshev Type II (uses only stopband ripple) ---
d_cheb2 = designfilt('lowpassiir', ...
    'DesignMethod','cheby2', ...
    'PassbandFrequency',fp, ...
    'StopbandFrequency',fs, ...
    'StopbandAttenuation',Rs);

% --- Elliptic (uses both ripple values) ---
d_ellip = designfilt('lowpassiir', ...
    'DesignMethod','ellip', ...
    'PassbandFrequency',fp, ...
    'StopbandFrequency',fs, ...
    'PassbandRipple',Rp, ...
    'StopbandAttenuation',Rs);

% Filter orders
order_equ = filtord(d_equ)
order_butt = filtord(d_butt)
order_cheb2 = filtord(d_cheb2)
order_ellip = filtord(d_ellip)

% Frequency responses
[H1,w] = freqz(d_equ,2048);
H2 = freqz(d_butt,2048);
H3 = freqz(d_cheb2,2048);
H4 = freqz(d_ellip,2048);

figure; hold on;
plot(w/pi,20*log10(abs(H1)));
plot(w/pi,20*log10(abs(H2)));
plot(w/pi,20*log10(abs(H3)));
plot(w/pi,20*log10(abs(H4)));

ylim([-100 2]);
xlabel('Normalized Frequency \omega/\pi');
ylabel('Magnitude (dB)');
legend('Equiripple','Butterworth','Chebyshev II','Elliptic');
title('Magnitude Responses of Minimum-Order Filters');
